export type {
    InteractivesType,
    Interactive,
    Quote,
    Advice,
    Recipe,
    Quiz,
    Mystery,
    InteractiveState,
    InteractiveType,
    InteractiveFieldNameType,
    Fact,
    Task,
} from './model/types/interactive';
export {
    useGetAdvicesQuery,
    useGetFactsQuery,
    useGetMysteriesQuery,
    useGetQuizzesQuery,
    useGetQuotesQuery,
    useGetRecipesQuery,
    useGetTasksQuery,
    usePostAdvicesMutation,
    usePostFactsMutation,
    usePostMysteriesMutation,
    usePostQuizzesMutation,
    usePostQuotesMutation,
    usePostRecipesMutation,
    usePostTasksMutation,
} from './api/interactiveApi';
